name: AWS Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
      id-token: write   # This is required for requesting the JWT
      contents: read    # This is required for actions/checkout

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1 # More information on this action can be found below in the 'AWS Credentials' section
        with:
          role-to-assume: arn:aws:iam::333681760334:role/icewhale-iam-role-github-action
          aws-region: us-east-1

      - name: Docker Login
        run: |
          aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 333681760334.dkr.ecr.us-east-1.amazonaws.com